### ISSUE TITLE
Scraper does not pull assessment from 'Examinations' section on ECP

### ISSUE THREAD

**Issue by ghost** [gricey432/unifinal#9]
If the course has a separate 'Individual Assignment' and 'Examination' section, the scraper does not grab both tables and won't be able to calculate percentages properly, Eg. INFS3208

**Comment by ghost** [comment]
I saw that you fixed this with a recent commit, but it must have not been deployed yet to the uqfinal site.

**Comment by gricey432** [comment]
@jaydonhansen I updated the scraper in c96ddd08218009558e4889d94b9f4003c1237a10 but didn't re-run it (it takes a long time). All the reported broken courses at that point had been in the BIOM codes, so I assumed it was something only happening in that school.

Task here is to re-run the UQ scraper

**Comment by ghost** [comment]
Ah understood. I wonder what's bottlenecking the performance of the scraper, in theory it's not that many requests but I might be overestimating how many requests UQ's server can deal with.

**Comment by gricey432** [comment]
It's 2 requests / offering (so about 3600 for UQ 2020-2). But to be a nice neighbour to uni websites we don't parallelise the requests. So not a huge amount of time, like an hour

**Comment by ghost** [comment]
That's fair, we don't want the subject old sign-on thing to happen again..

**Comment by gricey432** [comment]
I'll leave this open until all the data is corrected

**Comment by gricey432** [comment]
This should be fixed in 70424a4242c2239b03ecc4076f00a5a53830e814
